apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api 
    spec:
      containers:
        - image: ubuntu:24.04
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 5000
              name: http