---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api
spec:
  skipAnalysis: true
  analysis:
    interval: 30s # schedule interval (default 60s)
    threshold: 5 # max number of failed metric checks before rollback
    iterations: 10 # Prometheus checks based on
    metrics:
    - interval: 15s
      name: api-istio-error-rate
      thresholdRange:
        max: 1
    webhooks:
    - name: acceptance-test
      timeout: 5m
      type: pre-rollout
      url: http://flagger-loadtester.monitoring/
      metadata:
        cmd: curl -s http://api-canary.bootcamp/api-optimus/health
        type: bash
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: api-hpa
  progressDeadlineSeconds: 1500
  service:
    port: 80
    portDiscovery: true
    portName: http
    primary:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/probe_path: /api-optimus/health
        prometheus.io/probe_port: "80"
        prometheus.io/probe_scheme: http
    targetPort: 5000
    gateways:
    - mesh
    hosts:
    - api.bootcamp.svc.cluster.local
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
