apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 80m
            memory: 20Mi