apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
spec:
  template:
    spec:
      containers:
        - name: jnlp
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
