apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootcamp-devops-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ppr-bootcamp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/api/overlays/development
    repoURL: https://github.com/cnunez-occ/k8s-testing.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true